In [3]:
import pandas as pd
import numpy as np

nasdaqFile = 'C:/Users/efran/Documents/Data/IXIC.csv'
spFile = 'C:/Users/efran/Documents/Data/GSPC.csv'
googFile = 'C:/Users/efran/Documents/Data/GOOG.csv'
oilFile = 'C:/Users/efran/Documents/Data/USO.csv'
xomFile = 'C:/Users/efran/Documents/Data/XOM.csv'

In [4]:
def readFile(filename):
    data=pd.read_csv(filename,sep=",",usecols=[0,5],names=['Date', 'Price'],header=0)
    returns=np.array(data["Price"][:-1],np.float)/np.array(data["Price"][1:],np.float)-1
    data["Returns"]=np.append(returns,np.nan)
    data.index=data["Date"]
    return data

In [5]:
from sklearn.linear_model import SGDRegressor,LinearRegression

In [6]:
oilData = readFile(oilFile)
nasdaqData = readFile(nasdaqFile)
xomData = readFile(xomFile)

In [7]:
oilData

Date       Price   Returns
Date                                        
2016-12-01  2016-12-01   11.720000  0.072278
2016-11-01  2016-11-01   10.930000  0.037987
2016-10-01  2016-10-01   10.530000 -0.036597
2016-09-01  2016-09-01   10.930000  0.055019
2016-08-01  2016-08-01   10.360000  0.061475
2016-07-01  2016-07-01    9.760000 -0.156439
2016-06-01  2016-06-01   11.570000 -0.025274
2016-05-01  2016-05-01   11.870000  0.050442
2016-04-01  2016-04-01   11.300000  0.164948
2016-03-01  2016-03-01    9.700000  0.077778
2016-02-01  2016-02-01    9.000000 -0.067358
2016-01-01  2016-01-01    9.650000 -0.122727
2015-12-01  2015-12-01   11.000000 -0.149265
2015-11-01  2015-11-01   12.930000 -0.126941
2015-10-01  2015-10-01   14.810000  0.008856
2015-09-01  2015-09-01   14.680000 -0.076149
2015-08-01  2015-08-01   15.890000  0.019243
2015-07-01  2015-07-01   15.590000 -0.215795
2015-06-01  2015-06-01   19.879999 -0.021172
2015-05-01  2015-05-01   20.309999 -0.009751
2015-04-01  2015-04-01   20.510000  0.217933
2015-03-01  2015-03-01   16.840000 -0.069613
2015-02-01  2015-02-01   18.100000  0.015713
2015-01-01  2015-01-01   17.820000 -0.124754
2014-12-01  2014-12-01   20.360001 -0.204066
2014-11-01  2014-11-01   25.580000 -0.164871
2014-10-01  2014-10-01   30.629999 -0.109852
2014-09-01  2014-09-01   34.410000 -0.037752
2014-08-01  2014-08-01   35.759998 -0.015419
2014-07-01  2014-07-01   36.320000 -0.065844
...                ...         ...       ...
2008-10-01  2008-10-01   55.590000 -0.322156
2008-09-01  2008-09-01   82.010002 -0.116938
2008-08-01  2008-08-01   92.870003 -0.071207
2008-07-01  2008-07-01   99.989998 -0.120271
2008-06-01  2008-06-01  113.660004  0.102853
2008-05-01  2008-05-01  103.059998  0.114162
2008-04-01  2008-04-01   92.500000  0.136922
2008-03-01  2008-03-01   81.360001  0.011689
2008-02-01  2008-02-01   80.419998  0.111541
2008-01-01  2008-01-01   72.349998 -0.045011
2007-12-01  2007-12-01   75.760002  0.083679
2007-11-01  2007-11-01   69.910004 -0.045858
2007-10-01  2007-10-01   73.269997  0.171383
2007-09-01  2007-09-01   62.549999  0.121370
2007-08-01  2007-08-01   55.779999 -0.046984
2007-07-01  2007-07-01   58.529999  0.104340
2007-06-01  2007-06-01   53.000000  0.082516
2007-05-01  2007-05-01   48.959999 -0.044497
2007-04-01  2007-04-01   51.240002 -0.039550
2007-03-01  2007-03-01   53.349998  0.042399
2007-02-01  2007-02-01   51.180000  0.060945
2007-01-01  2007-01-01   48.240002 -0.065116
2006-12-01  2006-12-01   51.599998 -0.054599
2006-11-01  2006-11-01   54.580002  0.047601
2006-10-01  2006-10-01   52.099998 -0.085965
2006-09-01  2006-09-01   57.000000 -0.120370
2006-08-01  2006-08-01   64.800003 -0.067894
2006-07-01  2006-07-01   69.519997 -0.003583
2006-06-01  2006-06-01   69.769997  0.030120
2006-05-01  2006-05-01   67.730003       NaN

[128 rows x 3 columns]

In [8]:
oilDataUnfilled = oilData["Returns"][0:-1]

In [9]:
nasdaqDataFilled = nasdaqData["Returns"][0:-1]

In [10]:
nasdaqDataFilled = nasdaqDataFilled[0:len(oilDataUnfilled)]

In [11]:
combined = np.vstack((nasdaqDataFilled, oilDataUnfilled))

In [12]:
combined

array([[ 0.02269479,  0.02592723, -0.02312874,  0.01894794,  0.00989714,
         0.06596773, -0.02129726,  0.03616271, -0.01940311,  0.06842986,
        -0.01213711, -0.07857554, -0.01982116,  0.01086716,  0.09384736,
        -0.0400086 , -0.06153522,  0.0283564 , -0.01640221,  0.0260269 ,
         0.00827199, -0.01262205,  0.07082471, -0.02128558, -0.01159941,
         0.03474383,  0.03056714, -0.01896829,  0.04817187, -0.00871338,
         0.03902307,  0.03112363, -0.02010726, -0.02533121,  0.0497676 ,
        -0.01740893,  0.02874461,  0.03576283,  0.03930287,  0.05058954,
        -0.01006516,  0.0655609 , -0.01523764,  0.03818801,  0.01875123,
         0.03396317,  0.00574771,  0.0406092 ,  0.0030795 ,  0.01108749,
        -0.04460518,  0.01606477,  0.043354  ,  0.00152296,  0.03809586,
        -0.07189564, -0.01462362,  0.04202386,  0.05439179,  0.08010679,
        -0.00579703, -0.02386738,  0.11137287, -0.06360248, -0.06418561,
        -0.00617992, -0.02178959, -0.01330762,  0.0

In [13]:
len(combined)

2

In [14]:
combined=combined.T

In [15]:
len(combined)

127

In [16]:
combined

array([[ 0.02269479,  0.07227813],
       [ 0.02592723,  0.0379867 ],
       [-0.02312874, -0.03659652],
       [ 0.01894794,  0.05501931],
       [ 0.00989714,  0.06147541],
       [ 0.06596773, -0.15643907],
       [-0.02129726, -0.0252738 ],
       [ 0.03616271,  0.05044248],
       [-0.01940311,  0.16494845],
       [ 0.06842986,  0.07777778],
       [-0.01213711, -0.06735751],
       [-0.07857554, -0.12272727],
       [-0.01982116, -0.14926527],
       [ 0.01086716, -0.12694126],
       [ 0.09384736,  0.00885559],
       [-0.0400086 , -0.07614852],
       [-0.06153522,  0.0192431 ],
       [ 0.0283564 , -0.21579473],
       [-0.01640221, -0.02117184],
       [ 0.0260269 , -0.00975139],
       [ 0.00827199,  0.21793349],
       [-0.01262205, -0.06961326],
       [ 0.07082471,  0.01571268],
       [-0.02128558, -0.12475446],
       [-0.01159941, -0.20406564],
       [ 0.03474383, -0.16487101],
       [ 0.03056714, -0.10985182],
       [-0.01896829, -0.03775162],
       [ 0.04817187,

In [17]:
xomDataFilled = xomData["Returns"][0:-1][0:len(oilDataUnfilled)]

In [18]:
from sklearn import datasets, linear_model

xomNasdaqOilModel=linear_model.LinearRegression()

In [19]:
xomNasdaqOilModel.fit(combined,xomDataFilled)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [20]:
xomNasdaqOilModel.score(combined,xomDataFilled)

0.22531988211947085

In [21]:
import statsmodels.api as sm

In [22]:
X = sm.add_constant(combined)

In [23]:
X

array([[  1.00000000e+00,   2.26947938e-02,   7.22781336e-02],
       [  1.00000000e+00,   2.59272318e-02,   3.79867047e-02],
       [  1.00000000e+00,  -2.31287393e-02,  -3.65965233e-02],
       [  1.00000000e+00,   1.89479402e-02,   5.50193050e-02],
       [  1.00000000e+00,   9.89714191e-03,   6.14754098e-02],
       [  1.00000000e+00,   6.59677339e-02,  -1.56439067e-01],
       [  1.00000000e+00,  -2.12972559e-02,  -2.52737995e-02],
       [  1.00000000e+00,   3.61627075e-02,   5.04424779e-02],
       [  1.00000000e+00,  -1.94031096e-02,   1.64948454e-01],
       [  1.00000000e+00,   6.84298620e-02,   7.77777778e-02],
       [  1.00000000e+00,  -1.21371054e-02,  -6.73575130e-02],
       [  1.00000000e+00,  -7.85755408e-02,  -1.22727273e-01],
       [  1.00000000e+00,  -1.98211604e-02,  -1.49265275e-01],
       [  1.00000000e+00,   1.08671624e-02,  -1.26941256e-01],
       [  1.00000000e+00,   9.38473623e-02,   8.85558583e-03],
       [  1.00000000e+00,  -4.00086036e-02,  -7.6148521

In [24]:
model=sm.OLS(xomDataFilled, X)

In [25]:
results = model.fit()

In [26]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                Returns   R-squared:                       0.225
Model:                            OLS   Adj. R-squared:                  0.213
Method:                 Least Squares   F-statistic:                     18.03
Date:                Thu, 06 Jul 2017   Prob (F-statistic):           1.34e-07
Time:                        18:11:47   Log-Likelihood:                 223.60
No. Observations:                 127   AIC:                            -441.2
Df Residuals:                     124   BIC:                            -432.7
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0055      0.004      1.437      0.1